name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
              node-version: '22'

        - name: Install all dependencies
          run: npm run install-all

        - name: Install dev dependencies
          run: npm install

        # - name: Run backend tests
        #   run: npm test --prefix backend

        # - name: Run frontend tests
        #   run: npm test --prefix frontend

        - name: Run Both
          run: npm run start